// Copyright (c) 2025 渟雲. All rights reserved.
//
// Licensed under the TOSSRCU 2025.9 License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  https://raw.githubusercontent.com/M3351AN/M3351AN/9e7630a8511b8306c62952ca1a4f1ce0cc5b784a/LICENSE
//
// -----------------------------------------------------------------------------
// File: dll_proxy.h
// Author: 渟雲(quq[at]outlook.it6)
// Date: 2026-5-28
//
// Description:
//   This file includes functions of Dll Proxy.
//
// -----------------------------------------------------------------------------
#pragma once

#ifndef DLL_PROXY_H
#define DLL_PROXY_H
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif  // WIN32_LEAN_AND_MEAN

#include <Windows.h>

#ifdef _WIN64
#define MAKE_EXPORT(func) \
  "/EXPORT:" func "=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\user32.dll." func
#define MAKE_EXPORT_ORDINAL(func, ord)                                    \
  "/EXPORT:" func                                                         \
  "=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\user32.dll.#" #ord ",@" #ord \
  ",NONAME"
#else
#define MAKE_EXPORT(func) \
  "/EXPORT:" func "=\\\\.\\GLOBALROOT\\SystemRoot\\SysWOW64\\user32.dll." func
#define MAKE_EXPORT_ORDINAL(func, ord)                                    \
  "/EXPORT:" func                                                         \
  "=\\\\.\\GLOBALROOT\\SystemRoot\\SysWOW64\\user32.dll.#" #ord ",@" #ord \
  ",NONAME"
#endif  // _WIN64

#pragma comment(linker, MAKE_EXPORT("ActivateKeyboardLayout"))
#pragma comment(linker, MAKE_EXPORT("AddClipboardFormatListener"))
#pragma comment(linker, MAKE_EXPORT("AddVisualIdentifier"))
#pragma comment(linker, MAKE_EXPORT("AdjustWindowRect"))
#pragma comment(linker, MAKE_EXPORT("AdjustWindowRectEx"))
#pragma comment(linker, MAKE_EXPORT("AdjustWindowRectExForDpi"))
#pragma comment(linker, MAKE_EXPORT("AlignRects"))
#pragma comment(linker, MAKE_EXPORT("AllowForegroundActivation"))
#pragma comment(linker, MAKE_EXPORT("AllowSetForegroundWindow"))
#pragma comment(linker, MAKE_EXPORT("AnimateWindow"))
#pragma comment(linker, MAKE_EXPORT("AnyPopup"))
#pragma comment(linker, MAKE_EXPORT("AppendMenuA"))
#pragma comment(linker, MAKE_EXPORT("AppendMenuW"))
#pragma comment(linker, MAKE_EXPORT("ApplyWindowAction"))
#pragma comment(linker, MAKE_EXPORT("AreDpiAwarenessContextsEqual"))
#pragma comment(linker, MAKE_EXPORT("ArrangeIconicWindows"))
#pragma comment(linker, MAKE_EXPORT("AttachThreadInput"))
#pragma comment(linker, MAKE_EXPORT("BeginDeferWindowPos"))
#pragma comment(linker, MAKE_EXPORT("BeginPaint"))
#pragma comment(linker, MAKE_EXPORT("BlockInput"))
#pragma comment(linker, MAKE_EXPORT("BringWindowToTop"))
#pragma comment(linker, MAKE_EXPORT("BroadcastSystemMessage"))
#pragma comment(linker, MAKE_EXPORT("BroadcastSystemMessageA"))
#pragma comment(linker, MAKE_EXPORT("BroadcastSystemMessageExA"))
#pragma comment(linker, MAKE_EXPORT("BroadcastSystemMessageExW"))
#pragma comment(linker, MAKE_EXPORT("BroadcastSystemMessageW"))
#pragma comment(linker, MAKE_EXPORT("BuildReasonArray"))
#pragma comment(linker, MAKE_EXPORT("CalcMenuBar"))
#pragma comment(linker, MAKE_EXPORT("CalculatePopupWindowPosition"))
#pragma comment(linker, MAKE_EXPORT("CallMsgFilter"))
#pragma comment(linker, MAKE_EXPORT("CallMsgFilterA"))
#pragma comment(linker, MAKE_EXPORT("CallMsgFilterW"))
#pragma comment(linker, MAKE_EXPORT("CallNextHookEx"))
#pragma comment(linker, MAKE_EXPORT("CallWindowProcA"))
#pragma comment(linker, MAKE_EXPORT("CallWindowProcW"))
#pragma comment(linker, MAKE_EXPORT("CancelShutdown"))
#pragma comment(linker, MAKE_EXPORT("CascadeChildWindows"))
#pragma comment(linker, MAKE_EXPORT("CascadeWindows"))
#pragma comment(linker, MAKE_EXPORT("ChangeClipboardChain"))
#pragma comment(linker, MAKE_EXPORT("ChangeDisplaySettingsA"))
#pragma comment(linker, MAKE_EXPORT("ChangeDisplaySettingsExA"))
#pragma comment(linker, MAKE_EXPORT("ChangeDisplaySettingsExW"))
#pragma comment(linker, MAKE_EXPORT("ChangeDisplaySettingsW"))
#pragma comment(linker, MAKE_EXPORT("ChangeMenuA"))
#pragma comment(linker, MAKE_EXPORT("ChangeMenuW"))
#pragma comment(linker, MAKE_EXPORT("ChangeWindowMessageFilter"))
#pragma comment(linker, MAKE_EXPORT("ChangeWindowMessageFilterEx"))
#pragma comment(linker, MAKE_EXPORT("CharLowerA"))
#pragma comment(linker, MAKE_EXPORT("CharLowerBuffA"))
#pragma comment(linker, MAKE_EXPORT("CharLowerBuffW"))
#pragma comment(linker, MAKE_EXPORT("CharLowerW"))
#pragma comment(linker, MAKE_EXPORT("CharNextA"))
#pragma comment(linker, MAKE_EXPORT("CharNextExA"))
#pragma comment(linker, MAKE_EXPORT("CharNextW"))
#pragma comment(linker, MAKE_EXPORT("CharPrevA"))
#pragma comment(linker, MAKE_EXPORT("CharPrevExA"))
#pragma comment(linker, MAKE_EXPORT("CharPrevW"))
#pragma comment(linker, MAKE_EXPORT("CharToOemA"))
#pragma comment(linker, MAKE_EXPORT("CharToOemBuffA"))
#pragma comment(linker, MAKE_EXPORT("CharToOemBuffW"))
#pragma comment(linker, MAKE_EXPORT("CharToOemW"))
#pragma comment(linker, MAKE_EXPORT("CharUpperA"))
#pragma comment(linker, MAKE_EXPORT("CharUpperBuffA"))
#pragma comment(linker, MAKE_EXPORT("CharUpperBuffW"))
#pragma comment(linker, MAKE_EXPORT("CharUpperW"))
#pragma comment(linker, MAKE_EXPORT("CheckBannedOneCoreTransformApi"))
#pragma comment(linker, MAKE_EXPORT("CheckDBCSEnabledExt"))
#pragma comment(linker, MAKE_EXPORT("CheckDlgButton"))
#pragma comment(linker, MAKE_EXPORT("CheckMenuItem"))
#pragma comment(linker, MAKE_EXPORT("CheckMenuRadioItem"))
#pragma comment(linker, MAKE_EXPORT("CheckProcessForClipboardAccess"))
#pragma comment(linker, MAKE_EXPORT("CheckProcessSession"))
#pragma comment(linker, MAKE_EXPORT("CheckRadioButton"))
#pragma comment(linker, MAKE_EXPORT("CheckWindowThreadDesktop"))
#pragma comment(linker, MAKE_EXPORT("ChildWindowFromPoint"))
#pragma comment(linker, MAKE_EXPORT("ChildWindowFromPointEx"))
#pragma comment(linker, MAKE_EXPORT("CliImmSetHotKey"))
#pragma comment(linker, MAKE_EXPORT("ClientThreadSetup"))
#pragma comment(linker, MAKE_EXPORT("ClientToScreen"))
#pragma comment(linker, MAKE_EXPORT("ClipCursor"))
#pragma comment(linker, MAKE_EXPORT("CloseClipboard"))
#pragma comment(linker, MAKE_EXPORT("CloseDesktop"))
#pragma comment(linker, MAKE_EXPORT("CloseGestureInfoHandle"))
#pragma comment(linker, MAKE_EXPORT("CloseTouchInputHandle"))
#pragma comment(linker, MAKE_EXPORT("CloseWindow"))
#pragma comment(linker, MAKE_EXPORT("CloseWindowStation"))
#pragma comment(linker, MAKE_EXPORT("ConsoleControl"))
#pragma comment(linker, MAKE_EXPORT("ControlMagnification"))
#pragma comment(linker, MAKE_EXPORT("ConvertPrimaryPointerToMouseDrag"))
#pragma comment(linker, MAKE_EXPORT("ConvertToInterceptWindow"))
#pragma comment(linker, MAKE_EXPORT("CopyAcceleratorTableA"))
#pragma comment(linker, MAKE_EXPORT("CopyAcceleratorTableW"))
#pragma comment(linker, MAKE_EXPORT("CopyIcon"))
#pragma comment(linker, MAKE_EXPORT("CopyImage"))
#pragma comment(linker, MAKE_EXPORT("CopyRect"))
#pragma comment(linker, MAKE_EXPORT("CountClipboardFormats"))
#pragma comment(linker, MAKE_EXPORT("CreateAcceleratorTableA"))
#pragma comment(linker, MAKE_EXPORT("CreateAcceleratorTableW"))
#pragma comment(linker, MAKE_EXPORT("CreateCaret"))
#pragma comment(linker, MAKE_EXPORT("CreateCursor"))
#pragma comment(linker, MAKE_EXPORT("CreateDCompositionHwndTarget"))
#pragma comment(linker, MAKE_EXPORT("CreateDesktopA"))
#pragma comment(linker, MAKE_EXPORT("CreateDesktopExA"))
#pragma comment(linker, MAKE_EXPORT("CreateDesktopExW"))
#pragma comment(linker, MAKE_EXPORT("CreateDesktopW"))
#pragma comment(linker, MAKE_EXPORT("CreateDialogIndirectParamA"))
#pragma comment(linker, MAKE_EXPORT("CreateDialogIndirectParamAorW"))
#pragma comment(linker, MAKE_EXPORT("CreateDialogIndirectParamW"))
#pragma comment(linker, MAKE_EXPORT("CreateDialogParamA"))
#pragma comment(linker, MAKE_EXPORT("CreateDialogParamW"))
#pragma comment(linker, MAKE_EXPORT("CreateIcon"))
#pragma comment(linker, MAKE_EXPORT("CreateIconFromResource"))
#pragma comment(linker, MAKE_EXPORT("CreateIconFromResourceEx"))
#pragma comment(linker, MAKE_EXPORT("CreateIconIndirect"))
#pragma comment(linker, MAKE_EXPORT("CreateMDIWindowA"))
#pragma comment(linker, MAKE_EXPORT("CreateMDIWindowW"))
#pragma comment(linker, MAKE_EXPORT("CreateMenu"))
#pragma comment(linker, MAKE_EXPORT("CreatePopupMenu"))
#pragma comment(linker, MAKE_EXPORT("CreateSyntheticPointerDevice"))
#pragma comment(linker, MAKE_EXPORT("CreateSyntheticPointerDevice2"))
#pragma comment(linker, MAKE_EXPORT("CreateSystemThreads"))
#pragma comment(linker, MAKE_EXPORT("CreateWindowExA"))
#pragma comment(linker, MAKE_EXPORT("CreateWindowExW"))
#pragma comment(linker, MAKE_EXPORT("CreateWindowInBand"))
#pragma comment(linker, MAKE_EXPORT("CreateWindowInBandEx"))
#pragma comment(linker, MAKE_EXPORT("CreateWindowIndirect"))
#pragma comment(linker, MAKE_EXPORT("CreateWindowStationA"))
#pragma comment(linker, MAKE_EXPORT("CreateWindowStationW"))
#pragma comment(linker, MAKE_EXPORT("CsrBroadcastSystemMessageExW"))
#pragma comment(linker, MAKE_EXPORT("CtxInitUser32"))
#pragma comment(linker, MAKE_EXPORT("DdeAbandonTransaction"))
#pragma comment(linker, MAKE_EXPORT("DdeAccessData"))
#pragma comment(linker, MAKE_EXPORT("DdeAddData"))
#pragma comment(linker, MAKE_EXPORT("DdeClientTransaction"))
#pragma comment(linker, MAKE_EXPORT("DdeCmpStringHandles"))
#pragma comment(linker, MAKE_EXPORT("DdeConnect"))
#pragma comment(linker, MAKE_EXPORT("DdeConnectList"))
#pragma comment(linker, MAKE_EXPORT("DdeCreateDataHandle"))
#pragma comment(linker, MAKE_EXPORT("DdeCreateStringHandleA"))
#pragma comment(linker, MAKE_EXPORT("DdeCreateStringHandleW"))
#pragma comment(linker, MAKE_EXPORT("DdeDisconnect"))
#pragma comment(linker, MAKE_EXPORT("DdeDisconnectList"))
#pragma comment(linker, MAKE_EXPORT("DdeEnableCallback"))
#pragma comment(linker, MAKE_EXPORT("DdeFreeDataHandle"))
#pragma comment(linker, MAKE_EXPORT("DdeFreeStringHandle"))
#pragma comment(linker, MAKE_EXPORT("DdeGetData"))
#pragma comment(linker, MAKE_EXPORT("DdeGetLastError"))
#pragma comment(linker, MAKE_EXPORT("DdeGetQualityOfService"))
#pragma comment(linker, MAKE_EXPORT("DdeImpersonateClient"))
#pragma comment(linker, MAKE_EXPORT("DdeInitializeA"))
#pragma comment(linker, MAKE_EXPORT("DdeInitializeW"))
#pragma comment(linker, MAKE_EXPORT("DdeKeepStringHandle"))
#pragma comment(linker, MAKE_EXPORT("DdeNameService"))
#pragma comment(linker, MAKE_EXPORT("DdePostAdvise"))
#pragma comment(linker, MAKE_EXPORT("DdeQueryConvInfo"))
#pragma comment(linker, MAKE_EXPORT("DdeQueryNextServer"))
#pragma comment(linker, MAKE_EXPORT("DdeQueryStringA"))
#pragma comment(linker, MAKE_EXPORT("DdeQueryStringW"))
#pragma comment(linker, MAKE_EXPORT("DdeReconnect"))
#pragma comment(linker, MAKE_EXPORT("DdeSetQualityOfService"))
#pragma comment(linker, MAKE_EXPORT("DdeSetUserHandle"))
#pragma comment(linker, MAKE_EXPORT("DdeUnaccessData"))
#pragma comment(linker, MAKE_EXPORT("DdeUninitialize"))
#pragma comment(linker, MAKE_EXPORT("DefDlgProcA"))
#pragma comment(linker, MAKE_EXPORT("DefDlgProcW"))
#pragma comment(linker, MAKE_EXPORT("DefFrameProcA"))
#pragma comment(linker, MAKE_EXPORT("DefFrameProcW"))
#pragma comment(linker, MAKE_EXPORT("DefMDIChildProcA"))
#pragma comment(linker, MAKE_EXPORT("DefMDIChildProcW"))
#pragma comment(linker, MAKE_EXPORT("DefRawInputProc"))
#pragma comment(linker, MAKE_EXPORT("DefWindowProcA"))
#pragma comment(linker, MAKE_EXPORT("DefWindowProcW"))
#pragma comment(linker, MAKE_EXPORT("DeferWindowPos"))
#pragma comment(linker, MAKE_EXPORT("DeferWindowPosAndBand"))
#pragma comment(linker, MAKE_EXPORT("DelegateInput"))
#pragma comment(linker, MAKE_EXPORT("DeleteMenu"))
#pragma comment(linker, MAKE_EXPORT("DeregisterShellHookWindow"))
#pragma comment(linker, MAKE_EXPORT("DestroyAcceleratorTable"))
#pragma comment(linker, MAKE_EXPORT("DestroyCaret"))
#pragma comment(linker, MAKE_EXPORT("DestroyCursor"))
#pragma comment(linker, MAKE_EXPORT("DestroyDCompositionHwndTarget"))
#pragma comment(linker, MAKE_EXPORT("DestroyIcon"))
#pragma comment(linker, MAKE_EXPORT("DestroyMenu"))
#pragma comment(linker, MAKE_EXPORT("DestroyReasons"))
#pragma comment(linker, MAKE_EXPORT("DestroySyntheticPointerDevice"))
#pragma comment(linker, MAKE_EXPORT("DestroyWindow"))
#pragma comment(linker, MAKE_EXPORT("DialogBoxIndirectParamA"))
#pragma comment(linker, MAKE_EXPORT("DialogBoxIndirectParamAorW"))
#pragma comment(linker, MAKE_EXPORT("DialogBoxIndirectParamW"))
#pragma comment(linker, MAKE_EXPORT("DialogBoxParamA"))
#pragma comment(linker, MAKE_EXPORT("DialogBoxParamW"))
#pragma comment(linker, MAKE_EXPORT("DisableProcessWindowsGhosting"))
#pragma comment(linker, MAKE_EXPORT("DispatchMessageA"))
#pragma comment(linker, MAKE_EXPORT("DispatchMessageW"))
#pragma comment(linker, MAKE_EXPORT("DisplayConfigGetDeviceInfo"))
#pragma comment(linker, MAKE_EXPORT("DisplayConfigSetDeviceInfo"))
#pragma comment(linker, MAKE_EXPORT("DisplayExitWindowsWarnings"))
#pragma comment(linker, MAKE_EXPORT("DlgDirListA"))
#pragma comment(linker, MAKE_EXPORT("DlgDirListComboBoxA"))
#pragma comment(linker, MAKE_EXPORT("DlgDirListComboBoxW"))
#pragma comment(linker, MAKE_EXPORT("DlgDirListW"))
#pragma comment(linker, MAKE_EXPORT("DlgDirSelectComboBoxExA"))
#pragma comment(linker, MAKE_EXPORT("DlgDirSelectComboBoxExW"))
#pragma comment(linker, MAKE_EXPORT("DlgDirSelectExA"))
#pragma comment(linker, MAKE_EXPORT("DlgDirSelectExW"))
#pragma comment(linker, MAKE_EXPORT("DoSoundConnect"))
#pragma comment(linker, MAKE_EXPORT("DoSoundDisconnect"))
#pragma comment(linker, MAKE_EXPORT("DragDetect"))
#pragma comment(linker, MAKE_EXPORT("DragObject"))
#pragma comment(linker, MAKE_EXPORT("DrawAnimatedRects"))
#pragma comment(linker, MAKE_EXPORT("DrawCaption"))
#pragma comment(linker, MAKE_EXPORT("DrawCaptionTempA"))
#pragma comment(linker, MAKE_EXPORT("DrawCaptionTempW"))
#pragma comment(linker, MAKE_EXPORT("DrawEdge"))
#pragma comment(linker, MAKE_EXPORT("DrawFocusRect"))
#pragma comment(linker, MAKE_EXPORT("DrawFrame"))
#pragma comment(linker, MAKE_EXPORT("DrawFrameControl"))
#pragma comment(linker, MAKE_EXPORT("DrawIcon"))
#pragma comment(linker, MAKE_EXPORT("DrawIconEx"))
#pragma comment(linker, MAKE_EXPORT("DrawMenuBar"))
#pragma comment(linker, MAKE_EXPORT("DrawMenuBarTemp"))
#pragma comment(linker, MAKE_EXPORT("DrawStateA"))
#pragma comment(linker, MAKE_EXPORT("DrawStateW"))
#pragma comment(linker, MAKE_EXPORT("DrawTextA"))
#pragma comment(linker, MAKE_EXPORT("DrawTextExA"))
#pragma comment(linker, MAKE_EXPORT("DrawTextExW"))
#pragma comment(linker, MAKE_EXPORT("DrawTextW"))
#pragma comment(linker, MAKE_EXPORT("DwmGetDxRgn"))
#pragma comment(linker, MAKE_EXPORT("DwmGetDxSharedSurface"))
#pragma comment(linker, MAKE_EXPORT("DwmGetRemoteSessionOcclusionEvent"))
#pragma comment(linker, MAKE_EXPORT("DwmGetRemoteSessionOcclusionState"))
#pragma comment(linker, MAKE_EXPORT("DwmKernelShutdown"))
#pragma comment(linker, MAKE_EXPORT("DwmKernelStartup"))
#pragma comment(linker, MAKE_EXPORT("DwmLockScreenUpdates"))
#pragma comment(linker, MAKE_EXPORT("DwmValidateWindow"))
#pragma comment(linker, MAKE_EXPORT("DwmWindowNotificationsEnabled"))
#pragma comment(linker, MAKE_EXPORT("EditWndProc"))
#pragma comment(linker, MAKE_EXPORT("EmptyClipboard"))
#pragma comment(linker, MAKE_EXPORT("EnableMenuItem"))
#pragma comment(linker, MAKE_EXPORT("EnableMouseInPointer"))
#pragma comment(linker, MAKE_EXPORT("EnableNonClientDpiScaling"))
#pragma comment(linker, MAKE_EXPORT("EnableOneCoreTransformMode"))
#pragma comment(linker, MAKE_EXPORT("EnableScrollBar"))
#pragma comment(linker, MAKE_EXPORT("EnableSessionForMMCSS"))
#pragma comment(linker, MAKE_EXPORT("EnableWindow"))
#pragma comment(linker, \
                MAKE_EXPORT("EnableWindowShellWindowManagementBehavior"))
#pragma comment(linker, MAKE_EXPORT("EndDeferWindowPos"))
#pragma comment(linker, MAKE_EXPORT("EndDeferWindowPosEx"))
#pragma comment(linker, MAKE_EXPORT("EndDialog"))
#pragma comment(linker, MAKE_EXPORT("EndMenu"))
#pragma comment(linker, MAKE_EXPORT("EndPaint"))
#pragma comment(linker, MAKE_EXPORT("EndTask"))
#pragma comment(linker, MAKE_EXPORT("EnterMoveSizeLoop"))
#pragma comment(linker, MAKE_EXPORT("EnterReaderModeHelper"))
#pragma comment(linker, MAKE_EXPORT("EnumChildWindows"))
#pragma comment(linker, MAKE_EXPORT("EnumClipboardFormats"))
#pragma comment(linker, MAKE_EXPORT("EnumDesktopWindows"))
#pragma comment(linker, MAKE_EXPORT("EnumDesktopsA"))
#pragma comment(linker, MAKE_EXPORT("EnumDesktopsW"))
#pragma comment(linker, MAKE_EXPORT("EnumDisplayDevicesA"))
#pragma comment(linker, MAKE_EXPORT("EnumDisplayDevicesW"))
#pragma comment(linker, MAKE_EXPORT("EnumDisplayMonitors"))
#pragma comment(linker, MAKE_EXPORT("EnumDisplaySettingsA"))
#pragma comment(linker, MAKE_EXPORT("EnumDisplaySettingsExA"))
#pragma comment(linker, MAKE_EXPORT("EnumDisplaySettingsExW"))
#pragma comment(linker, MAKE_EXPORT("EnumDisplaySettingsW"))
#pragma comment(linker, MAKE_EXPORT("EnumPropsA"))
#pragma comment(linker, MAKE_EXPORT("EnumPropsExA"))
#pragma comment(linker, MAKE_EXPORT("EnumPropsExW"))
#pragma comment(linker, MAKE_EXPORT("EnumPropsW"))
#pragma comment(linker, MAKE_EXPORT("EnumThreadWindows"))
#pragma comment(linker, MAKE_EXPORT("EnumWindowStationsA"))
#pragma comment(linker, MAKE_EXPORT("EnumWindowStationsW"))
#pragma comment(linker, MAKE_EXPORT("EnumWindows"))
#pragma comment(linker, MAKE_EXPORT("EqualRect"))
#pragma comment(linker, MAKE_EXPORT("EvaluateProximityToPolygon"))
#pragma comment(linker, MAKE_EXPORT("EvaluateProximityToRect"))
#pragma comment(linker, MAKE_EXPORT("ExcludeUpdateRgn"))
#pragma comment(linker, MAKE_EXPORT("ExitWindowsEx"))
#pragma comment(linker, MAKE_EXPORT("FillRect"))
#pragma comment(linker, MAKE_EXPORT("FindWindowA"))
#pragma comment(linker, MAKE_EXPORT("FindWindowExA"))
#pragma comment(linker, MAKE_EXPORT("FindWindowExW"))
#pragma comment(linker, MAKE_EXPORT("FindWindowW"))
#pragma comment(linker, MAKE_EXPORT("FlashWindow"))
#pragma comment(linker, MAKE_EXPORT("FlashWindowEx"))
#pragma comment(linker, MAKE_EXPORT("FrameRect"))
#pragma comment(linker, MAKE_EXPORT("FreeDDElParam"))
#pragma comment(linker, MAKE_EXPORT("FrostCrashedWindow"))
#pragma comment(linker, MAKE_EXPORT("GetActiveWindow"))
#pragma comment(linker, MAKE_EXPORT("GetAltTabInfo"))
#pragma comment(linker, MAKE_EXPORT("GetAltTabInfoA"))
#pragma comment(linker, MAKE_EXPORT("GetAltTabInfoW"))
#pragma comment(linker, MAKE_EXPORT("GetAncestor"))
#pragma comment(linker, MAKE_EXPORT("GetAppCompatFlags"))
#pragma comment(linker, MAKE_EXPORT("GetAppCompatFlags2"))
#pragma comment(linker, MAKE_EXPORT("GetAsyncKeyState"))
#pragma comment(linker, MAKE_EXPORT("GetAutoRotationState"))
#pragma comment(linker, MAKE_EXPORT("GetAwarenessFromDpiAwarenessContext"))
#pragma comment(linker, MAKE_EXPORT("GetCIMSSM"))
#pragma comment(linker, MAKE_EXPORT("GetCapture"))
#pragma comment(linker, MAKE_EXPORT("GetCaretBlinkTime"))
#pragma comment(linker, MAKE_EXPORT("GetCaretPos"))
#pragma comment(linker, MAKE_EXPORT("GetClassInfoA"))
#pragma comment(linker, MAKE_EXPORT("GetClassInfoExA"))
#pragma comment(linker, MAKE_EXPORT("GetClassInfoExW"))
#pragma comment(linker, MAKE_EXPORT("GetClassInfoW"))
#pragma comment(linker, MAKE_EXPORT("GetClassLongA"))
#pragma comment(linker, MAKE_EXPORT("GetClassLongPtrA"))
#pragma comment(linker, MAKE_EXPORT("GetClassLongPtrW"))
#pragma comment(linker, MAKE_EXPORT("GetClassLongW"))
#pragma comment(linker, MAKE_EXPORT("GetClassNameA"))
#pragma comment(linker, MAKE_EXPORT("GetClassNameW"))
#pragma comment(linker, MAKE_EXPORT("GetClassWord"))
#pragma comment(linker, MAKE_EXPORT("GetClientRect"))
#pragma comment(linker, MAKE_EXPORT("GetClipCursor"))
#pragma comment(linker, MAKE_EXPORT("GetClipboardAccessToken"))
#pragma comment(linker, MAKE_EXPORT("GetClipboardData"))
#pragma comment(linker, MAKE_EXPORT("GetClipboardFormatNameA"))
#pragma comment(linker, MAKE_EXPORT("GetClipboardFormatNameW"))
#pragma comment(linker, MAKE_EXPORT("GetClipboardMetadata"))
#pragma comment(linker, MAKE_EXPORT("GetClipboardOwner"))
#pragma comment(linker, MAKE_EXPORT("GetClipboardSequenceNumber"))
#pragma comment(linker, MAKE_EXPORT("GetClipboardViewer"))
#pragma comment(linker, MAKE_EXPORT("GetComboBoxInfo"))
#pragma comment(linker, MAKE_EXPORT("GetCurrentInputMessageSource"))
#pragma comment(linker, MAKE_EXPORT("GetCurrentMonitorTopologyId"))
#pragma comment(linker, MAKE_EXPORT("GetCursor"))
#pragma comment(linker, MAKE_EXPORT("GetCursorFrameInfo"))
#pragma comment(linker, MAKE_EXPORT("GetCursorInfo"))
#pragma comment(linker, MAKE_EXPORT("GetCursorPos"))
#pragma comment(linker, MAKE_EXPORT("GetDC"))
#pragma comment(linker, MAKE_EXPORT("GetDCEx"))
#pragma comment(linker, MAKE_EXPORT("GetDCompositionHwndBitmap"))
#pragma comment(linker, MAKE_EXPORT("GetDesktopID"))
#pragma comment(linker, MAKE_EXPORT("GetDesktopWindow"))
#pragma comment(linker, MAKE_EXPORT("GetDialogBaseUnits"))
#pragma comment(linker, MAKE_EXPORT("GetDialogControlDpiChangeBehavior"))
#pragma comment(linker, MAKE_EXPORT("GetDialogDpiChangeBehavior"))
#pragma comment(linker, MAKE_EXPORT("GetDisplayAutoRotationPreferences"))
#pragma comment(linker, MAKE_EXPORT("GetDisplayConfigBufferSizes"))
#pragma comment(linker, MAKE_EXPORT("GetDlgCtrlID"))
#pragma comment(linker, MAKE_EXPORT("GetDlgItem"))
#pragma comment(linker, MAKE_EXPORT("GetDlgItemInt"))
#pragma comment(linker, MAKE_EXPORT("GetDlgItemTextA"))
#pragma comment(linker, MAKE_EXPORT("GetDlgItemTextW"))
#pragma comment(linker, MAKE_EXPORT("GetDoubleClickTime"))
#pragma comment(linker, MAKE_EXPORT("GetDpiAwarenessContextForProcess"))
#pragma comment(linker, MAKE_EXPORT("GetDpiForMonitorInternal"))
#pragma comment(linker, MAKE_EXPORT("GetDpiForSystem"))
#pragma comment(linker, MAKE_EXPORT("GetDpiForWindow"))
#pragma comment(linker, MAKE_EXPORT("GetDpiFromDpiAwarenessContext"))
#pragma comment(linker, MAKE_EXPORT("GetExtendedPointerDeviceProperty"))
#pragma comment(linker, MAKE_EXPORT("GetFocus"))
#pragma comment(linker, MAKE_EXPORT("GetForegroundWindow"))
#pragma comment(linker, MAKE_EXPORT("GetGUIThreadInfo"))
#pragma comment(linker, MAKE_EXPORT("GetGestureConfig"))
#pragma comment(linker, MAKE_EXPORT("GetGestureExtraArgs"))
#pragma comment(linker, MAKE_EXPORT("GetGestureInfo"))
#pragma comment(linker, MAKE_EXPORT("GetGuiResources"))
#pragma comment(linker, MAKE_EXPORT("GetIconInfo"))
#pragma comment(linker, MAKE_EXPORT("GetIconInfoExA"))
#pragma comment(linker, MAKE_EXPORT("GetIconInfoExW"))
#pragma comment(linker, MAKE_EXPORT("GetInputDesktop"))
#pragma comment(linker, MAKE_EXPORT("GetInputLocaleInfo"))
#pragma comment(linker, MAKE_EXPORT("GetInputState"))
#pragma comment(linker, MAKE_EXPORT("GetInternalWindowPos"))
#pragma comment(linker, MAKE_EXPORT("GetKBCodePage"))
#pragma comment(linker, MAKE_EXPORT("GetKeyNameTextA"))
#pragma comment(linker, MAKE_EXPORT("GetKeyNameTextW"))
#pragma comment(linker, MAKE_EXPORT("GetKeyState"))
#pragma comment(linker, MAKE_EXPORT("GetKeyboardLayout"))
#pragma comment(linker, MAKE_EXPORT("GetKeyboardLayoutList"))
#pragma comment(linker, MAKE_EXPORT("GetKeyboardLayoutNameA"))
#pragma comment(linker, MAKE_EXPORT("GetKeyboardLayoutNameW"))
#pragma comment(linker, MAKE_EXPORT("GetKeyboardState"))
#pragma comment(linker, MAKE_EXPORT("GetKeyboardType"))
#pragma comment(linker, MAKE_EXPORT("GetLastActivePopup"))
#pragma comment(linker, MAKE_EXPORT("GetLastInputInfo"))
#pragma comment(linker, MAKE_EXPORT("GetLayeredWindowAttributes"))
#pragma comment(linker, MAKE_EXPORT("GetListBoxInfo"))
#pragma comment(linker, MAKE_EXPORT("GetMagnificationDesktopColorEffect"))
#pragma comment(linker, MAKE_EXPORT("GetMagnificationDesktopMagnification"))
#pragma comment(linker, MAKE_EXPORT("GetMagnificationDesktopSamplingMode"))
#pragma comment(linker, MAKE_EXPORT("GetMagnificationLensCtxInformation"))
#pragma comment(linker, MAKE_EXPORT("GetMenu"))
#pragma comment(linker, MAKE_EXPORT("GetMenuBarInfo"))
#pragma comment(linker, MAKE_EXPORT("GetMenuCheckMarkDimensions"))
#pragma comment(linker, MAKE_EXPORT("GetMenuContextHelpId"))
#pragma comment(linker, MAKE_EXPORT("GetMenuDefaultItem"))
#pragma comment(linker, MAKE_EXPORT("GetMenuInfo"))
#pragma comment(linker, MAKE_EXPORT("GetMenuItemCount"))
#pragma comment(linker, MAKE_EXPORT("GetMenuItemID"))
#pragma comment(linker, MAKE_EXPORT("GetMenuItemInfoA"))
#pragma comment(linker, MAKE_EXPORT("GetMenuItemInfoW"))
#pragma comment(linker, MAKE_EXPORT("GetMenuItemRect"))
#pragma comment(linker, MAKE_EXPORT("GetMenuState"))
#pragma comment(linker, MAKE_EXPORT("GetMenuStringA"))
#pragma comment(linker, MAKE_EXPORT("GetMenuStringW"))
#pragma comment(linker, MAKE_EXPORT("GetMessageA"))
#pragma comment(linker, MAKE_EXPORT("GetMessageExtraInfo"))
#pragma comment(linker, MAKE_EXPORT("GetMessagePos"))
#pragma comment(linker, MAKE_EXPORT("GetMessageTime"))
#pragma comment(linker, MAKE_EXPORT("GetMessageW"))
#pragma comment(linker, MAKE_EXPORT("GetMonitorInfoA"))
#pragma comment(linker, MAKE_EXPORT("GetMonitorInfoW"))
#pragma comment(linker, MAKE_EXPORT("GetMouseMovePointsEx"))
#pragma comment(linker, MAKE_EXPORT("GetNextDlgGroupItem"))
#pragma comment(linker, MAKE_EXPORT("GetNextDlgTabItem"))
#pragma comment(linker, MAKE_EXPORT("GetOpenClipboardWindow"))
#pragma comment(linker, MAKE_EXPORT("GetParent"))
#pragma comment(linker, MAKE_EXPORT("GetPhysicalCursorPos"))
#pragma comment(linker, MAKE_EXPORT("GetPointerCursorId"))
#pragma comment(linker, MAKE_EXPORT("GetPointerDevice"))
#pragma comment(linker, MAKE_EXPORT("GetPointerDeviceCursors"))
#pragma comment(linker, MAKE_EXPORT("GetPointerDeviceInputSpace"))
#pragma comment(linker, MAKE_EXPORT("GetPointerDeviceOrientation"))
#pragma comment(linker, MAKE_EXPORT("GetPointerDeviceProperties"))
#pragma comment(linker, MAKE_EXPORT("GetPointerDeviceRects"))
#pragma comment(linker, MAKE_EXPORT("GetPointerDevices"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFrameArrivalTimes"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFrameInfo"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFrameInfoHistory"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFramePenInfo"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFramePenInfoHistory"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFrameTimes"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFrameTouchInfo"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFrameTouchInfoHistory"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFrameTouchpadInfo"))
#pragma comment(linker, MAKE_EXPORT("GetPointerFrameTouchpadInfoHistory"))
#pragma comment(linker, MAKE_EXPORT("GetPointerInfo"))
#pragma comment(linker, MAKE_EXPORT("GetPointerInfoHistory"))
#pragma comment(linker, MAKE_EXPORT("GetPointerInputTransform"))
#pragma comment(linker, MAKE_EXPORT("GetPointerPenInfo"))
#pragma comment(linker, MAKE_EXPORT("GetPointerPenInfoHistory"))
#pragma comment(linker, MAKE_EXPORT("GetPointerTouchInfo"))
#pragma comment(linker, MAKE_EXPORT("GetPointerTouchInfoHistory"))
#pragma comment(linker, MAKE_EXPORT("GetPointerTouchpadInfo"))
#pragma comment(linker, MAKE_EXPORT("GetPointerTouchpadInfoHistory"))
#pragma comment(linker, MAKE_EXPORT("GetPointerType"))
#pragma comment(linker, MAKE_EXPORT("GetPriorityClipboardFormat"))
#pragma comment(linker, MAKE_EXPORT("GetProcessDefaultLayout"))
#pragma comment(linker, MAKE_EXPORT("GetProcessDpiAwarenessInternal"))
#pragma comment(linker, MAKE_EXPORT("GetProcessUIContextInformation"))
#pragma comment(linker, MAKE_EXPORT("GetProcessWindowStation"))
#pragma comment(linker, MAKE_EXPORT("GetProgmanWindow"))
#pragma comment(linker, MAKE_EXPORT("GetPropA"))
#pragma comment(linker, MAKE_EXPORT("GetPropW"))
#pragma comment(linker, MAKE_EXPORT("GetQueueStatus"))
#pragma comment(linker, MAKE_EXPORT("GetRawInputBuffer"))
#pragma comment(linker, MAKE_EXPORT("GetRawInputData"))
#pragma comment(linker, MAKE_EXPORT("GetRawInputDeviceInfoA"))
#pragma comment(linker, MAKE_EXPORT("GetRawInputDeviceInfoW"))
#pragma comment(linker, MAKE_EXPORT("GetRawInputDeviceList"))
#pragma comment(linker, MAKE_EXPORT("GetRawPointerDeviceData"))
#pragma comment(linker, MAKE_EXPORT("GetReasonTitleFromReasonCode"))
#pragma comment(linker, MAKE_EXPORT("GetRegisteredRawInputDevices"))
#pragma comment(linker, MAKE_EXPORT("GetScrollBarInfo"))
#pragma comment(linker, MAKE_EXPORT("GetScrollInfo"))
#pragma comment(linker, MAKE_EXPORT("GetScrollPos"))
#pragma comment(linker, MAKE_EXPORT("GetScrollRange"))
#pragma comment(linker, MAKE_EXPORT("GetSendMessageReceiver"))
#pragma comment(linker, MAKE_EXPORT("GetShellChangeNotifyWindow"))
#pragma comment(linker, MAKE_EXPORT("GetShellWindow"))
#pragma comment(linker, MAKE_EXPORT("GetSubMenu"))
#pragma comment(linker, MAKE_EXPORT("GetSysColor"))
#pragma comment(linker, MAKE_EXPORT("GetSysColorBrush"))
#pragma comment(linker, MAKE_EXPORT("GetSystemDpiForProcess"))
#pragma comment(linker, MAKE_EXPORT("GetSystemMenu"))
#pragma comment(linker, MAKE_EXPORT("GetSystemMetrics"))
#pragma comment(linker, MAKE_EXPORT("GetSystemMetricsForDpi"))
#pragma comment(linker, MAKE_EXPORT("GetTabbedTextExtentA"))
#pragma comment(linker, MAKE_EXPORT("GetTabbedTextExtentW"))
#pragma comment(linker, MAKE_EXPORT("GetTaskmanWindow"))
#pragma comment(linker, MAKE_EXPORT("GetThreadDesktop"))
#pragma comment(linker, MAKE_EXPORT("GetThreadDpiAwarenessContext"))
#pragma comment(linker, MAKE_EXPORT("GetThreadDpiHostingBehavior"))
#pragma comment(linker, MAKE_EXPORT("GetTitleBarInfo"))
#pragma comment(linker, MAKE_EXPORT("GetTopLevelWindow"))
#pragma comment(linker, MAKE_EXPORT("GetTopWindow"))
#pragma comment(linker, MAKE_EXPORT("GetTouchInputInfo"))
#pragma comment(linker, MAKE_EXPORT("GetUnpredictedMessagePos"))
#pragma comment(linker, MAKE_EXPORT("GetUpdateRect"))
#pragma comment(linker, MAKE_EXPORT("GetUpdateRgn"))
#pragma comment(linker, MAKE_EXPORT("GetUpdatedClipboardFormats"))
#pragma comment(linker, MAKE_EXPORT("GetUserObjectInformationA"))
#pragma comment(linker, MAKE_EXPORT("GetUserObjectInformationW"))
#pragma comment(linker, MAKE_EXPORT("GetUserObjectSecurity"))
#pragma comment(linker, MAKE_EXPORT("GetWinStationInfo"))
#pragma comment(linker, MAKE_EXPORT("GetWindow"))
#pragma comment(linker, MAKE_EXPORT("GetWindowBand"))
#pragma comment(linker, MAKE_EXPORT("GetWindowCompositionAttribute"))
#pragma comment(linker, MAKE_EXPORT("GetWindowCompositionInfo"))
#pragma comment(linker, MAKE_EXPORT("GetWindowContextHelpId"))
#pragma comment(linker, MAKE_EXPORT("GetWindowDC"))
#pragma comment(linker, MAKE_EXPORT("GetWindowDisplayAffinity"))
#pragma comment(linker, MAKE_EXPORT("GetWindowDpiAwarenessContext"))
#pragma comment(linker, MAKE_EXPORT("GetWindowDpiHostingBehavior"))
#pragma comment(linker, MAKE_EXPORT("GetWindowFeedbackSetting"))
#pragma comment(linker, MAKE_EXPORT("GetWindowInfo"))
#pragma comment(linker, MAKE_EXPORT("GetWindowLongA"))
#pragma comment(linker, MAKE_EXPORT("GetWindowLongPtrA"))
#pragma comment(linker, MAKE_EXPORT("GetWindowLongPtrW"))
#pragma comment(linker, MAKE_EXPORT("GetWindowLongW"))
#pragma comment(linker, MAKE_EXPORT("GetWindowMinimizeRect"))
#pragma comment(linker, MAKE_EXPORT("GetWindowModuleFileName"))
#pragma comment(linker, MAKE_EXPORT("GetWindowModuleFileNameA"))
#pragma comment(linker, MAKE_EXPORT("GetWindowModuleFileNameW"))
#pragma comment(linker, MAKE_EXPORT("GetWindowPlacement"))
#pragma comment(linker, MAKE_EXPORT("GetWindowProcessHandle"))
#pragma comment(linker, MAKE_EXPORT("GetWindowRect"))
#pragma comment(linker, MAKE_EXPORT("GetWindowRgn"))
#pragma comment(linker, MAKE_EXPORT("GetWindowRgnBox"))
#pragma comment(linker, MAKE_EXPORT("GetWindowRgnEx"))
#pragma comment(linker, MAKE_EXPORT("GetWindowTextA"))
#pragma comment(linker, MAKE_EXPORT("GetWindowTextLengthA"))
#pragma comment(linker, MAKE_EXPORT("GetWindowTextLengthW"))
#pragma comment(linker, MAKE_EXPORT("GetWindowTextW"))
#pragma comment(linker, MAKE_EXPORT("GetWindowThreadProcessId"))
#pragma comment(linker, MAKE_EXPORT("GetWindowWord"))
#pragma comment(linker, MAKE_EXPORT("GhostWindowFromHungWindow"))
#pragma comment(linker, MAKE_EXPORT("GrayStringA"))
#pragma comment(linker, MAKE_EXPORT("GrayStringW"))
#pragma comment(linker, MAKE_EXPORT("HandleDelegatedInput"))
#pragma comment(linker, MAKE_EXPORT("HideCaret"))
#pragma comment(linker, MAKE_EXPORT("HiliteMenuItem"))
#pragma comment(linker, MAKE_EXPORT("HungWindowFromGhostWindow"))
#pragma comment(linker, MAKE_EXPORT("IMPGetIMEA"))
#pragma comment(linker, MAKE_EXPORT("IMPGetIMEW"))
#pragma comment(linker, MAKE_EXPORT("IMPQueryIMEA"))
#pragma comment(linker, MAKE_EXPORT("IMPQueryIMEW"))
#pragma comment(linker, MAKE_EXPORT("IMPSetIMEA"))
#pragma comment(linker, MAKE_EXPORT("IMPSetIMEW"))
#pragma comment(linker, MAKE_EXPORT("ImpersonateDdeClientWindow"))
#pragma comment(linker, MAKE_EXPORT("InSendMessage"))
#pragma comment(linker, MAKE_EXPORT("InSendMessageEx"))
#pragma comment(linker, MAKE_EXPORT("InflateRect"))
#pragma comment(linker, MAKE_EXPORT("InheritWindowMonitor"))
#pragma comment(linker, MAKE_EXPORT("InitDManipHook"))
#pragma comment(linker, MAKE_EXPORT("InitializeGenericHidInjection"))
#pragma comment(linker, MAKE_EXPORT("InitializeInputDeviceInjection"))
#pragma comment(linker, MAKE_EXPORT("InitializeLpkHooks"))
#pragma comment(linker, MAKE_EXPORT("InitializePointerDeviceInjection"))
#pragma comment(linker, MAKE_EXPORT("InitializePointerDeviceInjectionEx"))
#pragma comment(linker, MAKE_EXPORT("InitializeTouchInjection"))
#pragma comment(linker, MAKE_EXPORT("InjectDeviceInput"))
#pragma comment(linker, MAKE_EXPORT("InjectGenericHidInput"))
#pragma comment(linker, MAKE_EXPORT("InjectKeyboardInput"))
#pragma comment(linker, MAKE_EXPORT("InjectMouseInput"))
#pragma comment(linker, MAKE_EXPORT("InjectPointerInput"))
#pragma comment(linker, MAKE_EXPORT("InjectSyntheticPointerInput"))
#pragma comment(linker, MAKE_EXPORT("InjectTouchInput"))
#pragma comment(linker, MAKE_EXPORT("InputSpaceRegionFromPoint"))
#pragma comment(linker, MAKE_EXPORT("InsertMenuA"))
#pragma comment(linker, MAKE_EXPORT("InsertMenuItemA"))
#pragma comment(linker, MAKE_EXPORT("InsertMenuItemW"))
#pragma comment(linker, MAKE_EXPORT("InsertMenuW"))
#pragma comment(linker, MAKE_EXPORT("InternalGetWindowIcon"))
#pragma comment(linker, MAKE_EXPORT("InternalGetWindowText"))
#pragma comment(linker, MAKE_EXPORT("IntersectRect"))
#pragma comment(linker, MAKE_EXPORT("InvalidateRect"))
#pragma comment(linker, MAKE_EXPORT("InvalidateRgn"))
#pragma comment(linker, MAKE_EXPORT("InvertRect"))
#pragma comment(linker, MAKE_EXPORT("IsCharAlphaA"))
#pragma comment(linker, MAKE_EXPORT("IsCharAlphaNumericA"))
#pragma comment(linker, MAKE_EXPORT("IsCharAlphaNumericW"))
#pragma comment(linker, MAKE_EXPORT("IsCharAlphaW"))
#pragma comment(linker, MAKE_EXPORT("IsCharLowerA"))
#pragma comment(linker, MAKE_EXPORT("IsCharLowerW"))
#pragma comment(linker, MAKE_EXPORT("IsCharUpperA"))
#pragma comment(linker, MAKE_EXPORT("IsCharUpperW"))
#pragma comment(linker, MAKE_EXPORT("IsChild"))
#pragma comment(linker, MAKE_EXPORT("IsClipboardFormatAvailable"))
#pragma comment(linker, MAKE_EXPORT("IsDialogMessage"))
#pragma comment(linker, MAKE_EXPORT("IsDialogMessageA"))
#pragma comment(linker, MAKE_EXPORT("IsDialogMessageW"))
#pragma comment(linker, MAKE_EXPORT("IsDlgButtonChecked"))
#pragma comment(linker, MAKE_EXPORT("IsGUIThread"))
#pragma comment(linker, MAKE_EXPORT("IsHungAppWindow"))
#pragma comment(linker, MAKE_EXPORT("IsIconic"))
#pragma comment(linker, MAKE_EXPORT("IsImmersiveProcess"))
#pragma comment(linker, MAKE_EXPORT("IsInDesktopWindowBand"))
#pragma comment(linker, MAKE_EXPORT("IsInterceptWindow"))
#pragma comment(linker, MAKE_EXPORT("IsMenu"))
#pragma comment(linker, MAKE_EXPORT("IsMouseInPointerEnabled"))
#pragma comment(linker, MAKE_EXPORT("IsOneCoreTransformMode"))
#pragma comment(linker, MAKE_EXPORT("IsProcessDPIAware"))
#pragma comment(linker, MAKE_EXPORT("IsRectEmpty"))
#pragma comment(linker, MAKE_EXPORT("IsSETEnabled"))
#pragma comment(linker, MAKE_EXPORT("IsServerSideWindow"))
#pragma comment(linker, MAKE_EXPORT("IsThreadDesktopComposited"))
#pragma comment(linker, MAKE_EXPORT("IsThreadMessageQueueAttached"))
#pragma comment(linker, MAKE_EXPORT("IsThreadTSFEventAware"))
#pragma comment(linker, MAKE_EXPORT("IsTopLevelWindow"))
#pragma comment(linker, MAKE_EXPORT("IsTouchWindow"))
#pragma comment(linker, MAKE_EXPORT("IsValidDpiAwarenessContext"))
#pragma comment(linker, MAKE_EXPORT("IsWinEventHookInstalled"))
#pragma comment(linker, MAKE_EXPORT("IsWindow"))
#pragma comment(linker, MAKE_EXPORT("IsWindowArranged"))
#pragma comment(linker, MAKE_EXPORT("IsWindowDisplayChangeSuppressed"))
#pragma comment(linker, MAKE_EXPORT("IsWindowEnabled"))
#pragma comment(linker, MAKE_EXPORT("IsWindowInDestroy"))
#pragma comment(linker, MAKE_EXPORT("IsWindowRedirectedForPrint"))
#pragma comment(linker, MAKE_EXPORT("IsWindowUnicode"))
#pragma comment(linker, MAKE_EXPORT("IsWindowVisible"))
#pragma comment(linker, MAKE_EXPORT("IsWow64Message"))
#pragma comment(linker, MAKE_EXPORT("IsZoomed"))
#pragma comment(linker, MAKE_EXPORT("KillTimer"))
#pragma comment(linker, MAKE_EXPORT("LoadAcceleratorsA"))
#pragma comment(linker, MAKE_EXPORT("LoadAcceleratorsW"))
#pragma comment(linker, MAKE_EXPORT("LoadBitmapA"))
#pragma comment(linker, MAKE_EXPORT("LoadBitmapW"))
#pragma comment(linker, MAKE_EXPORT("LoadCursorA"))
#pragma comment(linker, MAKE_EXPORT("LoadCursorFromFileA"))
#pragma comment(linker, MAKE_EXPORT("LoadCursorFromFileW"))
#pragma comment(linker, MAKE_EXPORT("LoadCursorW"))
#pragma comment(linker, MAKE_EXPORT("LoadIconA"))
#pragma comment(linker, MAKE_EXPORT("LoadIconW"))
#pragma comment(linker, MAKE_EXPORT("LoadImageA"))
#pragma comment(linker, MAKE_EXPORT("LoadImageW"))
#pragma comment(linker, MAKE_EXPORT("LoadKeyboardLayoutA"))
#pragma comment(linker, MAKE_EXPORT("LoadKeyboardLayoutEx"))
#pragma comment(linker, MAKE_EXPORT("LoadKeyboardLayoutW"))
#pragma comment(linker, MAKE_EXPORT("LoadLocalFonts"))
#pragma comment(linker, MAKE_EXPORT("LoadMenuA"))
#pragma comment(linker, MAKE_EXPORT("LoadMenuIndirectA"))
#pragma comment(linker, MAKE_EXPORT("LoadMenuIndirectW"))
#pragma comment(linker, MAKE_EXPORT("LoadMenuW"))
#pragma comment(linker, MAKE_EXPORT("LoadRemoteFonts"))
#pragma comment(linker, MAKE_EXPORT("LoadStringA"))
#pragma comment(linker, MAKE_EXPORT("LoadStringW"))
#pragma comment(linker, MAKE_EXPORT("LockSetForegroundWindow"))
#pragma comment(linker, MAKE_EXPORT("LockWindowStation"))
#pragma comment(linker, MAKE_EXPORT("LockWindowUpdate"))
#pragma comment(linker, MAKE_EXPORT("LockWorkStation"))
#pragma comment(linker, MAKE_EXPORT("LogicalToPhysicalPoint"))
#pragma comment(linker, MAKE_EXPORT("LogicalToPhysicalPointForPerMonitorDPI"))
#pragma comment(linker, MAKE_EXPORT("LookupIconIdFromDirectory"))
#pragma comment(linker, MAKE_EXPORT("LookupIconIdFromDirectoryEx"))
#pragma comment(linker, MAKE_EXPORT("MBToWCSEx"))
#pragma comment(linker, MAKE_EXPORT("MBToWCSExt"))
#pragma comment(linker, MAKE_EXPORT("MB_GetString"))
#pragma comment(linker, MAKE_EXPORT("MITGetCursorUpdateHandle"))
#pragma comment(linker, MAKE_EXPORT("MITSetLastInputRecipient"))
#pragma comment(linker, MAKE_EXPORT("MITSynthesizeTouchInput"))
#pragma comment(linker, MAKE_EXPORT("MakeThreadTSFEventAware"))
#pragma comment(linker, MAKE_EXPORT("MapDialogRect"))
#pragma comment(linker, MAKE_EXPORT("MapPointsByVisualIdentifier"))
#pragma comment(linker, MAKE_EXPORT("MapVirtualKeyA"))
#pragma comment(linker, MAKE_EXPORT("MapVirtualKeyExA"))
#pragma comment(linker, MAKE_EXPORT("MapVirtualKeyExW"))
#pragma comment(linker, MAKE_EXPORT("MapVirtualKeyW"))
#pragma comment(linker, MAKE_EXPORT("MapVisualRelativePoints"))
#pragma comment(linker, MAKE_EXPORT("MapWindowPoints"))
#pragma comment(linker, MAKE_EXPORT("MenuItemFromPoint"))
#pragma comment(linker, MAKE_EXPORT("MenuWindowProcA"))
#pragma comment(linker, MAKE_EXPORT("MenuWindowProcW"))
#pragma comment(linker, MAKE_EXPORT("MessageBeep"))
#pragma comment(linker, MAKE_EXPORT("MessageBoxA"))
#pragma comment(linker, MAKE_EXPORT("MessageBoxExA"))
#pragma comment(linker, MAKE_EXPORT("MessageBoxExW"))
#pragma comment(linker, MAKE_EXPORT("MessageBoxIndirectA"))
#pragma comment(linker, MAKE_EXPORT("MessageBoxIndirectW"))
#pragma comment(linker, MAKE_EXPORT("MessageBoxTimeoutA"))
#pragma comment(linker, MAKE_EXPORT("MessageBoxTimeoutW"))
#pragma comment(linker, MAKE_EXPORT("MessageBoxW"))
#pragma comment(linker, MAKE_EXPORT("ModifyMenuA"))
#pragma comment(linker, MAKE_EXPORT("ModifyMenuW"))
#pragma comment(linker, MAKE_EXPORT("MonitorFromPoint"))
#pragma comment(linker, MAKE_EXPORT("MonitorFromRect"))
#pragma comment(linker, MAKE_EXPORT("MonitorFromWindow"))
#pragma comment(linker, MAKE_EXPORT("MoveWindow"))
#pragma comment(linker, MAKE_EXPORT("MsgWaitForMultipleObjects"))
#pragma comment(linker, MAKE_EXPORT("MsgWaitForMultipleObjectsEx"))
#pragma comment(linker, MAKE_EXPORT("NotifyOverlayWindow"))
#pragma comment(linker, MAKE_EXPORT("NotifyWinEvent"))
#pragma comment(linker, MAKE_EXPORT("OemKeyScan"))
#pragma comment(linker, MAKE_EXPORT("OemToCharA"))
#pragma comment(linker, MAKE_EXPORT("OemToCharBuffA"))
#pragma comment(linker, MAKE_EXPORT("OemToCharBuffW"))
#pragma comment(linker, MAKE_EXPORT("OemToCharW"))
#pragma comment(linker, MAKE_EXPORT("OffsetRect"))
#pragma comment(linker, MAKE_EXPORT("OpenClipboard"))
#pragma comment(linker, MAKE_EXPORT("OpenDesktopA"))
#pragma comment(linker, MAKE_EXPORT("OpenDesktopW"))
#pragma comment(linker, MAKE_EXPORT("OpenIcon"))
#pragma comment(linker, MAKE_EXPORT("OpenInputDesktop"))
#pragma comment(linker, MAKE_EXPORT("OpenThreadDesktop"))
#pragma comment(linker, MAKE_EXPORT("OpenWindowStationA"))
#pragma comment(linker, MAKE_EXPORT("OpenWindowStationW"))
#pragma comment(linker, MAKE_EXPORT("PackDDElParam"))
#pragma comment(linker, MAKE_EXPORT("PackTouchHitTestingProximityEvaluation"))
#pragma comment(linker, MAKE_EXPORT("PaintDesktop"))
#pragma comment(linker, MAKE_EXPORT("PaintMenuBar"))
#pragma comment(linker, MAKE_EXPORT("PaintMonitor"))
#pragma comment(linker, MAKE_EXPORT("PeekMessageA"))
#pragma comment(linker, MAKE_EXPORT("PeekMessageW"))
#pragma comment(linker, MAKE_EXPORT("PhysicalToLogicalPoint"))
#pragma comment(linker, MAKE_EXPORT("PhysicalToLogicalPointForPerMonitorDPI"))
#pragma comment(linker, MAKE_EXPORT("PostMessageA"))
#pragma comment(linker, MAKE_EXPORT("PostMessageW"))
#pragma comment(linker, MAKE_EXPORT("PostQuitMessage"))
#pragma comment(linker, MAKE_EXPORT("PostThreadMessageA"))
#pragma comment(linker, MAKE_EXPORT("PostThreadMessageW"))
#pragma comment(linker, MAKE_EXPORT("PrintWindow"))
#pragma comment(linker, MAKE_EXPORT("PrivateExtractIconExA"))
#pragma comment(linker, MAKE_EXPORT("PrivateExtractIconExW"))
#pragma comment(linker, MAKE_EXPORT("PrivateExtractIconsA"))
#pragma comment(linker, MAKE_EXPORT("PrivateExtractIconsW"))
#pragma comment(linker, MAKE_EXPORT("PrivateRegisterICSProc"))
#pragma comment(linker, MAKE_EXPORT("PtInRect"))
#pragma comment(linker, MAKE_EXPORT("QueryBSDRWindow"))
#pragma comment(linker, MAKE_EXPORT("QueryDisplayConfig"))
#pragma comment(linker, MAKE_EXPORT("QuerySendMessage"))
#pragma comment(linker, MAKE_EXPORT("RIMAddInputObserver"))
#pragma comment(linker, MAKE_EXPORT("RIMAreSiblingDevices"))
#pragma comment(linker, MAKE_EXPORT("RIMDeviceIoControl"))
#pragma comment(linker, MAKE_EXPORT("RIMEnableMonitorMappingForDevice"))
#pragma comment(linker, MAKE_EXPORT("RIMFreeInputBuffer"))
#pragma comment(linker, MAKE_EXPORT("RIMGetDevicePreparsedData"))
#pragma comment(linker, MAKE_EXPORT("RIMGetDevicePreparsedDataLockfree"))
#pragma comment(linker, MAKE_EXPORT("RIMGetDeviceProperties"))
#pragma comment(linker, MAKE_EXPORT("RIMGetDevicePropertiesLockfree"))
#pragma comment(linker, MAKE_EXPORT("RIMGetPhysicalDeviceRect"))
#pragma comment(linker, MAKE_EXPORT("RIMGetSourceProcessId"))
#pragma comment(linker, MAKE_EXPORT("RIMObserveNextInput"))
#pragma comment(linker, MAKE_EXPORT("RIMOnAsyncPnpWorkNotification"))
#pragma comment(linker, MAKE_EXPORT("RIMOnPnpNotification"))
#pragma comment(linker, MAKE_EXPORT("RIMOnTimerNotification"))
#pragma comment(linker, MAKE_EXPORT("RIMQueryDevicePath"))
#pragma comment(linker, MAKE_EXPORT("RIMReadInput"))
#pragma comment(linker, MAKE_EXPORT("RIMRegisterForInput"))
#pragma comment(linker, MAKE_EXPORT("RIMRegisterForInputEx"))
#pragma comment(linker, MAKE_EXPORT("RIMRemoveInputObserver"))
#pragma comment(linker, MAKE_EXPORT("RIMSetExtendedDeviceProperty"))
#pragma comment(linker, MAKE_EXPORT("RIMSetTestModeStatus"))
#pragma comment(linker, MAKE_EXPORT("RIMUnregisterForInput"))
#pragma comment(linker, MAKE_EXPORT("RIMUpdateInputObserverRegistration"))
#pragma comment(linker, MAKE_EXPORT("RaiseLowerShellWindow"))
#pragma comment(linker, MAKE_EXPORT("RealChildWindowFromPoint"))
#pragma comment(linker, MAKE_EXPORT("RealGetWindowClass"))
#pragma comment(linker, MAKE_EXPORT("RealGetWindowClassA"))
#pragma comment(linker, MAKE_EXPORT("RealGetWindowClassW"))
#pragma comment(linker, MAKE_EXPORT("ReasonCodeNeedsBugID"))
#pragma comment(linker, MAKE_EXPORT("ReasonCodeNeedsComment"))
#pragma comment(linker, MAKE_EXPORT("RecordShutdownReason"))
#pragma comment(linker, MAKE_EXPORT("RedrawWindow"))
#pragma comment(linker, MAKE_EXPORT("RegisterBSDRWindow"))
#pragma comment(linker, MAKE_EXPORT("RegisterClassA"))
#pragma comment(linker, MAKE_EXPORT("RegisterClassExA"))
#pragma comment(linker, MAKE_EXPORT("RegisterClassExW"))
#pragma comment(linker, MAKE_EXPORT("RegisterClassW"))
#pragma comment(linker, MAKE_EXPORT("RegisterClipboardFormatA"))
#pragma comment(linker, MAKE_EXPORT("RegisterClipboardFormatW"))
#pragma comment(linker, MAKE_EXPORT("RegisterCloakedNotification"))
#pragma comment(linker, MAKE_EXPORT("RegisterDManipHook"))
#pragma comment(linker, MAKE_EXPORT("RegisterDeviceNotificationA"))
#pragma comment(linker, MAKE_EXPORT("RegisterDeviceNotificationW"))
#pragma comment(linker, MAKE_EXPORT("RegisterErrorReportingDialog"))
#pragma comment(linker, MAKE_EXPORT("RegisterForCustomDockTargets"))
#pragma comment(linker, MAKE_EXPORT("RegisterForTooltipDismissNotification"))
#pragma comment(linker, MAKE_EXPORT("RegisterFrostWindow"))
#pragma comment(linker, MAKE_EXPORT("RegisterGhostWindow"))
#pragma comment(linker, MAKE_EXPORT("RegisterHotKey"))
#pragma comment(linker, MAKE_EXPORT("RegisterLogonProcess"))
#pragma comment(linker, MAKE_EXPORT("RegisterMessagePumpHook"))
#pragma comment(linker, MAKE_EXPORT("RegisterPointerDeviceNotifications"))
#pragma comment(linker, MAKE_EXPORT("RegisterPointerInputTarget"))
#pragma comment(linker, MAKE_EXPORT("RegisterPointerInputTargetEx"))
#pragma comment(linker, MAKE_EXPORT("RegisterPowerSettingNotification"))
#pragma comment(linker, MAKE_EXPORT("RegisterRawInputDevices"))
#pragma comment(linker, MAKE_EXPORT("RegisterServicesProcess"))
#pragma comment(linker, MAKE_EXPORT("RegisterSessionPort"))
#pragma comment(linker, MAKE_EXPORT("RegisterShellHookWindow"))
#pragma comment(linker, MAKE_EXPORT("RegisterSuspendResumeNotification"))
#pragma comment(linker, MAKE_EXPORT("RegisterSystemThread"))
#pragma comment(linker, MAKE_EXPORT("RegisterTasklist"))
#pragma comment(linker, MAKE_EXPORT("RegisterTouchHitTestingWindow"))
#pragma comment(linker, MAKE_EXPORT("RegisterTouchWindow"))
#pragma comment(linker, MAKE_EXPORT("RegisterTouchpadCapableThread"))
#pragma comment(linker, MAKE_EXPORT("RegisterTouchpadCapableWindow"))
#pragma comment(linker, MAKE_EXPORT("RegisterUserApiHook"))
#pragma comment(linker, MAKE_EXPORT("RegisterWindowMessageA"))
#pragma comment(linker, MAKE_EXPORT("RegisterWindowMessageW"))
#pragma comment(linker, MAKE_EXPORT("ReleaseCapture"))
#pragma comment(linker, MAKE_EXPORT("ReleaseDC"))
#pragma comment(linker, MAKE_EXPORT("ReleaseDwmHitTestWaiters"))
#pragma comment(linker, MAKE_EXPORT("RemoveClipboardFormatListener"))
#pragma comment(linker, MAKE_EXPORT("RemoveInjectionDevice"))
#pragma comment(linker, MAKE_EXPORT("RemoveMenu"))
#pragma comment(linker, MAKE_EXPORT("RemovePropA"))
#pragma comment(linker, MAKE_EXPORT("RemovePropW"))
#pragma comment(linker, MAKE_EXPORT("RemoveThreadTSFEventAwareness"))
#pragma comment(linker, MAKE_EXPORT("RemoveVisualIdentifier"))
#pragma comment(linker, MAKE_EXPORT("ReplyMessage"))
#pragma comment(linker, MAKE_EXPORT("ReportInertia"))
#pragma comment(linker, MAKE_EXPORT("ResolveDesktopForWOW"))
#pragma comment(linker, MAKE_EXPORT("ReuseDDElParam"))
#pragma comment(linker, MAKE_EXPORT("ScreenToClient"))
#pragma comment(linker, MAKE_EXPORT("ScrollChildren"))
#pragma comment(linker, MAKE_EXPORT("ScrollDC"))
#pragma comment(linker, MAKE_EXPORT("ScrollWindow"))
#pragma comment(linker, MAKE_EXPORT("ScrollWindowEx"))
#pragma comment(linker, MAKE_EXPORT("SendDlgItemMessageA"))
#pragma comment(linker, MAKE_EXPORT("SendDlgItemMessageW"))
#pragma comment(linker, MAKE_EXPORT("SendIMEMessageExA"))
#pragma comment(linker, MAKE_EXPORT("SendIMEMessageExW"))
#pragma comment(linker, MAKE_EXPORT("SendInput"))
#pragma comment(linker, MAKE_EXPORT("SendMessageA"))
#pragma comment(linker, MAKE_EXPORT("SendMessageCallbackA"))
#pragma comment(linker, MAKE_EXPORT("SendMessageCallbackW"))
#pragma comment(linker, MAKE_EXPORT("SendMessageTimeoutA"))
#pragma comment(linker, MAKE_EXPORT("SendMessageTimeoutW"))
#pragma comment(linker, MAKE_EXPORT("SendMessageW"))
#pragma comment(linker, MAKE_EXPORT("SendNotifyMessageA"))
#pragma comment(linker, MAKE_EXPORT("SendNotifyMessageW"))
#pragma comment(linker, MAKE_EXPORT("SetActiveWindow"))
#pragma comment(linker, MAKE_EXPORT("SetAdditionalForegroundBoostProcesses"))
#pragma comment(linker, MAKE_EXPORT("SetCapture"))
#pragma comment(linker, MAKE_EXPORT("SetCaretBlinkTime"))
#pragma comment(linker, MAKE_EXPORT("SetCaretPos"))
#pragma comment(linker, MAKE_EXPORT("SetClassLongA"))
#pragma comment(linker, MAKE_EXPORT("SetClassLongPtrA"))
#pragma comment(linker, MAKE_EXPORT("SetClassLongPtrW"))
#pragma comment(linker, MAKE_EXPORT("SetClassLongW"))
#pragma comment(linker, MAKE_EXPORT("SetClassWord"))
#pragma comment(linker, MAKE_EXPORT("SetClipboardData"))
#pragma comment(linker, MAKE_EXPORT("SetClipboardViewer"))
#pragma comment(linker, MAKE_EXPORT("SetCoalescableTimer"))
#pragma comment(linker, MAKE_EXPORT("SetCoreWindow"))
#pragma comment(linker, MAKE_EXPORT("SetCoveredWindowStates"))
#pragma comment(linker, MAKE_EXPORT("SetCursor"))
#pragma comment(linker, MAKE_EXPORT("SetCursorContents"))
#pragma comment(linker, MAKE_EXPORT("SetCursorPos"))
#pragma comment(linker, MAKE_EXPORT("SetDebugErrorLevel"))
#pragma comment(linker, MAKE_EXPORT("SetDeskWallpaper"))
#pragma comment(linker, MAKE_EXPORT("SetDesktopColorTransform"))
#pragma comment(linker, MAKE_EXPORT("SetDialogControlDpiChangeBehavior"))
#pragma comment(linker, MAKE_EXPORT("SetDialogDpiChangeBehavior"))
#pragma comment(linker, MAKE_EXPORT("SetDisplayAutoRotationPreferences"))
#pragma comment(linker, MAKE_EXPORT("SetDisplayConfig"))
#pragma comment(linker, MAKE_EXPORT("SetDlgItemInt"))
#pragma comment(linker, MAKE_EXPORT("SetDlgItemTextA"))
#pragma comment(linker, MAKE_EXPORT("SetDlgItemTextW"))
#pragma comment(linker, MAKE_EXPORT("SetDoubleClickTime"))
#pragma comment(linker, MAKE_EXPORT("SetFeatureReportResponse"))
#pragma comment(linker, MAKE_EXPORT("SetFocus"))
#pragma comment(linker, \
                MAKE_EXPORT("SetForegroundRedirectionForActivationObject"))
#pragma comment(linker, MAKE_EXPORT("SetForegroundWindow"))
#pragma comment(linker, MAKE_EXPORT("SetFullscreenMagnifierOffsetsDWMUpdated"))
#pragma comment(linker, MAKE_EXPORT("SetGestureConfig"))
#pragma comment(linker, MAKE_EXPORT("SetInternalWindowPos"))
#pragma comment(linker, MAKE_EXPORT("SetKeyboardState"))
#pragma comment(linker, MAKE_EXPORT("SetLastErrorEx"))
#pragma comment(linker, MAKE_EXPORT("SetLayeredWindowAttributes"))
#pragma comment(linker, MAKE_EXPORT("SetMagnificationDesktopColorEffect"))
#pragma comment(linker, MAKE_EXPORT("SetMagnificationDesktopMagnification"))
#pragma comment( \
    linker, MAKE_EXPORT("SetMagnificationDesktopMagnifierOffsetsDWMUpdated"))
#pragma comment(linker, MAKE_EXPORT("SetMagnificationDesktopSamplingMode"))
#pragma comment(linker, MAKE_EXPORT("SetMagnificationLensCtxInformation"))
#pragma comment(linker, MAKE_EXPORT("SetMaxTouchpadSensitivity"))
#pragma comment(linker, MAKE_EXPORT("SetMenu"))
#pragma comment(linker, MAKE_EXPORT("SetMenuContextHelpId"))
#pragma comment(linker, MAKE_EXPORT("SetMenuDefaultItem"))
#pragma comment(linker, MAKE_EXPORT("SetMenuInfo"))
#pragma comment(linker, MAKE_EXPORT("SetMenuItemBitmaps"))
#pragma comment(linker, MAKE_EXPORT("SetMenuItemInfoA"))
#pragma comment(linker, MAKE_EXPORT("SetMenuItemInfoW"))
#pragma comment(linker, MAKE_EXPORT("SetMessageExtraInfo"))
#pragma comment(linker, MAKE_EXPORT("SetMessageQueue"))
#pragma comment(linker, MAKE_EXPORT("SetMirrorRendering"))
#pragma comment(linker, MAKE_EXPORT("SetParent"))
#pragma comment(linker, MAKE_EXPORT("SetPhysicalCursorPos"))
#pragma comment(linker, MAKE_EXPORT("SetPointerDeviceInputSpace"))
#pragma comment(linker, MAKE_EXPORT("SetProcessDPIAware"))
#pragma comment(linker, MAKE_EXPORT("SetProcessDefaultLayout"))
#pragma comment(linker, MAKE_EXPORT("SetProcessDpiAwarenessContext"))
#pragma comment(linker, MAKE_EXPORT("SetProcessDpiAwarenessInternal"))
#pragma comment(linker, MAKE_EXPORT("SetProcessLaunchForegroundPolicy"))
#pragma comment(linker, MAKE_EXPORT("SetProcessRestrictionExemption"))
#pragma comment(linker, MAKE_EXPORT("SetProcessWindowStation"))
#pragma comment(linker, MAKE_EXPORT("SetProgmanWindow"))
#pragma comment(linker, MAKE_EXPORT("SetPropA"))
#pragma comment(linker, MAKE_EXPORT("SetPropW"))
#pragma comment(linker, MAKE_EXPORT("SetRect"))
#pragma comment(linker, MAKE_EXPORT("SetRectEmpty"))
#pragma comment(linker, MAKE_EXPORT("SetScrollInfo"))
#pragma comment(linker, MAKE_EXPORT("SetScrollPos"))
#pragma comment(linker, MAKE_EXPORT("SetScrollRange"))
#pragma comment(linker, MAKE_EXPORT("SetShellChangeNotifyWindow"))
#pragma comment(linker, MAKE_EXPORT("SetShellWindow"))
#pragma comment(linker, MAKE_EXPORT("SetShellWindowEx"))
#pragma comment(linker, MAKE_EXPORT("SetSysColors"))
#pragma comment(linker, MAKE_EXPORT("SetSysColorsTemp"))
#pragma comment(linker, MAKE_EXPORT("SetSystemCursor"))
#pragma comment(linker, MAKE_EXPORT("SetSystemMenu"))
#pragma comment(linker, MAKE_EXPORT("SetTaskmanWindow"))
#pragma comment(linker, MAKE_EXPORT("SetThreadCursorCreationScaling"))
#pragma comment(linker, MAKE_EXPORT("SetThreadDesktop"))
#pragma comment(linker, MAKE_EXPORT("SetThreadDpiAwarenessContext"))
#pragma comment(linker, MAKE_EXPORT("SetThreadDpiHostingBehavior"))
#pragma comment(linker, MAKE_EXPORT("SetThreadInputBlocked"))
#pragma comment(linker, MAKE_EXPORT("SetTimer"))
#pragma comment(linker, MAKE_EXPORT("SetUserObjectCapability"))
#pragma comment(linker, MAKE_EXPORT("SetUserObjectInformationA"))
#pragma comment(linker, MAKE_EXPORT("SetUserObjectInformationW"))
#pragma comment(linker, MAKE_EXPORT("SetUserObjectSecurity"))
#pragma comment(linker, MAKE_EXPORT("SetWinEventHook"))
#pragma comment(linker, MAKE_EXPORT("SetWindowBand"))
#pragma comment(linker, MAKE_EXPORT("SetWindowCompositionAttribute"))
#pragma comment(linker, MAKE_EXPORT("SetWindowCompositionTransition"))
#pragma comment(linker, MAKE_EXPORT("SetWindowContextHelpId"))
#pragma comment(linker, MAKE_EXPORT("SetWindowDisplayAffinity"))
#pragma comment(linker, MAKE_EXPORT("SetWindowFeedbackSetting"))
#pragma comment(linker, MAKE_EXPORT("SetWindowLongA"))
#pragma comment(linker, MAKE_EXPORT("SetWindowLongPtrA"))
#pragma comment(linker, MAKE_EXPORT("SetWindowLongPtrW"))
#pragma comment(linker, MAKE_EXPORT("SetWindowLongW"))
#pragma comment(linker, MAKE_EXPORT("SetWindowMessageCapability"))
#pragma comment(linker, MAKE_EXPORT("SetWindowPlacement"))
#pragma comment(linker, MAKE_EXPORT("SetWindowPos"))
#pragma comment(linker, MAKE_EXPORT("SetWindowRgn"))
#pragma comment(linker, MAKE_EXPORT("SetWindowRgnEx"))
#pragma comment(linker, MAKE_EXPORT("SetWindowStationUser"))
#pragma comment(linker, MAKE_EXPORT("SetWindowTextA"))
#pragma comment(linker, MAKE_EXPORT("SetWindowTextW"))
#pragma comment(linker, MAKE_EXPORT("SetWindowWord"))
#pragma comment(linker, MAKE_EXPORT("SetWindowsHookA"))
#pragma comment(linker, MAKE_EXPORT("SetWindowsHookExA"))
#pragma comment(linker, MAKE_EXPORT("SetWindowsHookExAW"))
#pragma comment(linker, MAKE_EXPORT("SetWindowsHookExW"))
#pragma comment(linker, MAKE_EXPORT("SetWindowsHookW"))
#pragma comment(linker, MAKE_EXPORT("ShellForegroundBoostProcess"))
#pragma comment(linker, MAKE_EXPORT("ShellHandwritingDelegateInput"))
#pragma comment(linker, MAKE_EXPORT("ShellHandwritingHandleDelegatedInput"))
#pragma comment(linker, MAKE_EXPORT("ShellHandwritingUndelegateInput"))
#pragma comment(linker, MAKE_EXPORT("ShellMigrateWindow"))
#pragma comment(linker, MAKE_EXPORT("ShellRegisterHotKey"))
#pragma comment(linker, MAKE_EXPORT("ShellSetWindowPos"))
#pragma comment(linker, MAKE_EXPORT("ShowCaret"))
#pragma comment(linker, MAKE_EXPORT("ShowCursor"))
#pragma comment(linker, MAKE_EXPORT("ShowOwnedPopups"))
#pragma comment(linker, MAKE_EXPORT("ShowScrollBar"))
#pragma comment(linker, MAKE_EXPORT("ShowStartGlass"))
#pragma comment(linker, MAKE_EXPORT("ShowSystemCursor"))
#pragma comment(linker, MAKE_EXPORT("ShowWindow"))
#pragma comment(linker, MAKE_EXPORT("ShowWindowAsync"))
#pragma comment(linker, MAKE_EXPORT("ShutdownBlockReasonCreate"))
#pragma comment(linker, MAKE_EXPORT("ShutdownBlockReasonDestroy"))
#pragma comment(linker, MAKE_EXPORT("ShutdownBlockReasonQuery"))
#pragma comment(linker, MAKE_EXPORT("SignalRedirectionStartComplete"))
#pragma comment(linker, MAKE_EXPORT("SkipPointerFrameMessages"))
#pragma comment(linker, MAKE_EXPORT("SoftModalMessageBox"))
#pragma comment(linker, MAKE_EXPORT("SoundSentry"))
#pragma comment(linker, MAKE_EXPORT("SubtractRect"))
#pragma comment(linker, MAKE_EXPORT("SuppressWindowDisplayChange"))
#pragma comment(linker, MAKE_EXPORT("SwapMouseButton"))
#pragma comment(linker, MAKE_EXPORT("SwitchDesktop"))
#pragma comment(linker, MAKE_EXPORT("SwitchDesktopWithFade"))
#pragma comment(linker, MAKE_EXPORT("SwitchToThisWindow"))
#pragma comment(linker, MAKE_EXPORT("SystemParametersInfoA"))
#pragma comment(linker, MAKE_EXPORT("SystemParametersInfoForDpi"))
#pragma comment(linker, MAKE_EXPORT("SystemParametersInfoW"))
#pragma comment(linker, MAKE_EXPORT("TabbedTextOutA"))
#pragma comment(linker, MAKE_EXPORT("TabbedTextOutW"))
#pragma comment(linker, MAKE_EXPORT("TileChildWindows"))
#pragma comment(linker, MAKE_EXPORT("TileWindows"))
#pragma comment(linker, MAKE_EXPORT("ToAscii"))
#pragma comment(linker, MAKE_EXPORT("ToAsciiEx"))
#pragma comment(linker, MAKE_EXPORT("ToUnicode"))
#pragma comment(linker, MAKE_EXPORT("ToUnicodeEx"))
#pragma comment(linker, MAKE_EXPORT("TrackMouseEvent"))
#pragma comment(linker, MAKE_EXPORT("TrackPopupMenu"))
#pragma comment(linker, MAKE_EXPORT("TrackPopupMenuEx"))
#pragma comment(linker, MAKE_EXPORT("TranslateAccelerator"))
#pragma comment(linker, MAKE_EXPORT("TranslateAcceleratorA"))
#pragma comment(linker, MAKE_EXPORT("TranslateAcceleratorW"))
#pragma comment(linker, MAKE_EXPORT("TranslateMDISysAccel"))
#pragma comment(linker, MAKE_EXPORT("TranslateMessage"))
#pragma comment(linker, MAKE_EXPORT("TranslateMessageEx"))
#pragma comment(linker, MAKE_EXPORT("UndelegateInput"))
#pragma comment(linker, MAKE_EXPORT("UnhookWinEvent"))
#pragma comment(linker, MAKE_EXPORT("UnhookWindowsHook"))
#pragma comment(linker, MAKE_EXPORT("UnhookWindowsHookEx"))
#pragma comment(linker, MAKE_EXPORT("UnionRect"))
#pragma comment(linker, MAKE_EXPORT("UnloadKeyboardLayout"))
#pragma comment(linker, MAKE_EXPORT("UnlockWindowStation"))
#pragma comment(linker, MAKE_EXPORT("UnpackDDElParam"))
#pragma comment(linker, MAKE_EXPORT("UnregisterClassA"))
#pragma comment(linker, MAKE_EXPORT("UnregisterClassW"))
#pragma comment(linker, MAKE_EXPORT("UnregisterDeviceNotification"))
#pragma comment(linker, MAKE_EXPORT("UnregisterHotKey"))
#pragma comment(linker, MAKE_EXPORT("UnregisterMessagePumpHook"))
#pragma comment(linker, MAKE_EXPORT("UnregisterPointerInputTarget"))
#pragma comment(linker, MAKE_EXPORT("UnregisterPointerInputTargetEx"))
#pragma comment(linker, MAKE_EXPORT("UnregisterPowerSettingNotification"))
#pragma comment(linker, MAKE_EXPORT("UnregisterSessionPort"))
#pragma comment(linker, MAKE_EXPORT("UnregisterSuspendResumeNotification"))
#pragma comment(linker, MAKE_EXPORT("UnregisterTouchWindow"))
#pragma comment(linker, MAKE_EXPORT("UnregisterUserApiHook"))
#pragma comment(linker, MAKE_EXPORT("UpdateDefaultDesktopThumbnail"))
#pragma comment(linker, MAKE_EXPORT("UpdateLayeredWindow"))
#pragma comment(linker, MAKE_EXPORT("UpdateLayeredWindowIndirect"))
#pragma comment(linker, MAKE_EXPORT("UpdatePerUserSystemParameters"))
#pragma comment(linker, MAKE_EXPORT("UpdateWindow"))
#pragma comment(linker, MAKE_EXPORT("UpdateWindowInputSinkHints"))
#pragma comment(linker, MAKE_EXPORT("User32InitializeImmEntryTable"))
#pragma comment(linker, MAKE_EXPORT("UserClientDllInitialize"))
#pragma comment(linker, MAKE_EXPORT("UserHandleGrantAccess"))
#pragma comment(linker, MAKE_EXPORT("UserLpkPSMTextOut"))
#pragma comment(linker, MAKE_EXPORT("UserLpkTabbedTextOut"))
#pragma comment(linker, MAKE_EXPORT("UserRealizePalette"))
#pragma comment(linker, MAKE_EXPORT("UserRegisterWowHandlers"))
#pragma comment(linker, MAKE_EXPORT("VRipOutput"))
#pragma comment(linker, MAKE_EXPORT("VTagOutput"))
#pragma comment(linker, MAKE_EXPORT("ValidateRect"))
#pragma comment(linker, MAKE_EXPORT("ValidateRgn"))
#pragma comment(linker, MAKE_EXPORT("VkKeyScanA"))
#pragma comment(linker, MAKE_EXPORT("VkKeyScanExA"))
#pragma comment(linker, MAKE_EXPORT("VkKeyScanExW"))
#pragma comment(linker, MAKE_EXPORT("VkKeyScanW"))
#pragma comment(linker, MAKE_EXPORT("WCSToMBEx"))
#pragma comment(linker, MAKE_EXPORT("WINNLSEnableIME"))
#pragma comment(linker, MAKE_EXPORT("WINNLSGetEnableStatus"))
#pragma comment(linker, MAKE_EXPORT("WINNLSGetIMEHotkey"))
#pragma comment(linker, MAKE_EXPORT("WaitForInputIdle"))
#pragma comment(linker, MAKE_EXPORT("WaitForRedirectionStartComplete"))
#pragma comment(linker, MAKE_EXPORT("WaitMessage"))
#pragma comment(linker, MAKE_EXPORT("WinHelpA"))
#pragma comment(linker, MAKE_EXPORT("WinHelpW"))
#pragma comment(linker, MAKE_EXPORT("WindowFromDC"))
#pragma comment(linker, MAKE_EXPORT("WindowFromPhysicalPoint"))
#pragma comment(linker, MAKE_EXPORT("WindowFromPoint"))
#pragma comment(linker, MAKE_EXPORT("_UserTestTokenForInteractive"))
#pragma comment(linker, MAKE_EXPORT("gSharedInfo"))
#pragma comment(linker, MAKE_EXPORT("gapfnScSendMessage"))
#pragma comment(linker, MAKE_EXPORT("keybd_event"))
#pragma comment(linker, MAKE_EXPORT("mouse_event"))
#pragma comment(linker, MAKE_EXPORT("wsprintfA"))
#pragma comment(linker, MAKE_EXPORT("wsprintfW"))
#pragma comment(linker, MAKE_EXPORT("wvsprintfA"))
#pragma comment(linker, MAKE_EXPORT("wvsprintfW"))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy1502", 1502))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy1550", 1550))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy1551", 1551))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy1552", 1552))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy1554", 1554))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2001", 2001))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2002", 2002))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2005", 2005))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2010", 2010))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2506", 2506))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2507", 2507))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2508", 2508))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2509", 2509))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2510", 2510))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2511", 2511))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2512", 2512))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2513", 2513))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2514", 2514))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2515", 2515))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2516", 2516))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2517", 2517))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2518", 2518))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2519", 2519))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2520", 2520))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2522", 2522))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2523", 2523))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2524", 2524))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2525", 2525))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2526", 2526))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2527", 2527))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2529", 2529))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2530", 2530))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2531", 2531))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2532", 2532))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2533", 2533))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2534", 2534))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2535", 2535))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2536", 2536))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2537", 2537))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2538", 2538))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2539", 2539))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2540", 2540))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2541", 2541))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2544", 2544))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2545", 2545))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2546", 2546))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2548", 2548))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2549", 2549))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2550", 2550))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2552", 2552))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2553", 2553))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2554", 2554))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2555", 2555))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2556", 2556))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2557", 2557))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2558", 2558))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2559", 2559))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2560", 2560))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2561", 2561))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2563", 2563))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2564", 2564))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2565", 2565))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2566", 2566))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2567", 2567))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2568", 2568))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2569", 2569))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2570", 2570))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2572", 2572))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2573", 2573))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2574", 2574))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2575", 2575))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2576", 2576))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2578", 2578))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2579", 2579))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2581", 2581))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2582", 2582))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2584", 2584))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2585", 2585))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2586", 2586))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2587", 2587))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2588", 2588))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2589", 2589))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2590", 2590))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2591", 2591))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2592", 2592))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2593", 2593))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2594", 2594))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2595", 2595))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2597", 2597))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2598", 2598))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2599", 2599))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2600", 2600))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2606", 2606))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2608", 2608))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2609", 2609))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2610", 2610))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2611", 2611))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2612", 2612))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2613", 2613))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2614", 2614))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2615", 2615))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2616", 2616))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2617", 2617))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2618", 2618))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2619", 2619))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2620", 2620))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2621", 2621))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2622", 2622))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2627", 2627))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2633", 2633))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2634", 2634))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2635", 2635))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2636", 2636))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2637", 2637))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2638", 2638))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2639", 2639))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2640", 2640))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2641", 2641))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2642", 2642))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2643", 2643))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2644", 2644))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2645", 2645))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2647", 2647))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2648", 2648))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2649", 2649))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2650", 2650))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2651", 2651))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2652", 2652))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2653", 2653))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2656", 2656))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2657", 2657))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2658", 2658))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2659", 2659))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2661", 2661))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2669", 2669))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2670", 2670))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2695", 2695))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2700", 2700))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2703", 2703))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2704", 2704))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2705", 2705))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2706", 2706))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2707", 2707))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2708", 2708))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2709", 2709))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2710", 2710))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2711", 2711))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2712", 2712))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2713", 2713))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2714", 2714))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2715", 2715))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2716", 2716))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2803", 2803))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2805", 2805))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2807", 2807))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2808", 2808))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2809", 2809))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2810", 2810))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2812", 2812))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2813", 2813))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2814", 2814))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2815", 2815))
#pragma comment(linker, MAKE_EXPORT_ORDINAL("__proxy2816", 2816))

#endif // DLL_PROXY_H
