name: Sync GitHub Releases to Gitee

on:
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Create Gitee Release
        id: create_release
        run: |
          # 调用 Gitee API 创建 Release
          response=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "{
              \"access_token\": \"${{ secrets.GITEE_ACCESS_TOKEN }}\",
              \"tag_name\": \"${{ github.event.release.tag_name }}\",
              \"name\": \"${{ github.event.release.name }}\",
              \"body\": \"${{ github.event.release.body }}\",
              \"target_commitish\": \"main\"
            }" \
            https://gitee.com/api/v5/repos/TEIKUMO/SPT-Fuyu/releases)

          echo "API response: $response"

          # 提取 release_id
          release_id=$(echo $response | jq -r '.id')
          if [ "$release_id" = "null" ] || [ -z "$release_id" ]; then
            echo "Failed to create Gitee release"
            exit 1
          fi
          echo "release_id=$release_id" >> $GITHUB_OUTPUT

      - name: Upload Release Assets to Gitee
        if: steps.create_release.outputs.release_id != ''
        run: |
          release_id=${{ steps.create_release.outputs.release_id }}

          for asset in $(echo '${{ toJson(github.event.release.assets) }}' | jq -r '.[].browser_download_url'); do
            echo "Downloading $asset"
            wget -O asset_file "$asset"

            echo "Uploading to Gitee..."
            curl -s -X POST \
              -H "Content-Type: multipart/form-data" \
              -F "access_token=${{ secrets.GITEE_ACCESS_TOKEN }}" \
              -F "file=@asset_file" \
              https://gitee.com/api/v5/repos/TEIKUMO/SPT-Fuyu/releases/$release_id/attachments
          done
