name: Sync Latest Release to CDN Repo

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CDN repo
        uses: actions/checkout@v4
        with:
          repository: M3351AN/cdn
          token: ${{ secrets.CDN_REPO_TOKEN }}
          path: cdn

      - name: Download latest release assets
        run: |
          repo_name=${{ github.event.repository.name }}
          tag=${{ github.event.release.tag_name }}
          mkdir -p "cdn/$repo_name/$tag"
          cd "cdn/$repo_name/$tag"

          for asset in $(echo '${{ toJson(github.event.release.assets) }}' | jq -r '.[].browser_download_url'); do
            wget -q "$asset"
          done

      - name: Commit and Push to CDN repo
        run: |
          cd cdn
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync latest release ${{ github.event.release.tag_name }} from ${{ github.event.repository.name }}" || echo "No changes to commit"
          git push
